name: sam3_image
version: pre-alpha
parts:
  image_encoder: models/hbm/sam3_image_encoder.hbm
  text_encoder: models/hbm/sam3_text_encoder.hbm
  geometry_encoder: models/hbm/sam3_geometry_encoder.hbm
  detector: models/hbm/sam3_detector.hbm
  mask_decoder: models/hbm/sam3_mask_decoder.hbm
